# Generated by Django 2.0.2 on 2018-06-26 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20180626_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(help_text='Enter a brief description of the employee', max_length=1000)),
                ('age', models.IntegerField(help_text='Age of employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='dep_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='catalog.Employee'),
        ),
    ]
