# Generated by Django 2.0.2 on 2018-07-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
